"use client";
import { useState } from "react";
import { AllInput } from "../../ui/form-elements";
import SuccessDialog from "../success-dialog";
import { Button } from "@/components/ui/button";

const inputs = [
  {
    label: "Order Number",
    name: "orderNumber",
    type: "number",
    placeholder: "Automatically Generated by the system",
  },
  {
    label: "Procurement Type",
    name: "procurementType",
    type: "select",
    options: [
      "Vehicle Procurement",
      "Vehicle Part Procurement",
      "Service Procurement",
    ],
    placeholder: "Select Procurement Type",
  },
  {
    label: "Vendor Selection",
    name: "vendorSelection",
    type: "text",
    placeholder: "Enter Vendor Name",
  },
  {
    label: "Item Description",
    name: "itemDescription",
    type: "text",
    placeholder: "E.g N1000",
  },
  {
    label: "Quantity",
    name: "quantity",
    type: "number",
    placeholder: "Enter Number of Items.",
  },
  {
    label: "Expected Delivery Date",
    name: "expectedDeliveryDate",
    type: "date",
  },
  {
    label: "Budget Allocation",
    name: "budgetAllocation",
    type: "text",
    placeholder: "E.g N1000",
  },
  {
    label: "Priority Level",
    name: "priorityLevel",
    type: "select",
    options: ["Low", "Medium", "High"],
    placeholder: "Select Priority Level",
  },
];

const NewProcurementRequestForm = () => {
  const [formData, setFormData] = useState({});

  return (
    <form className="flex flex-col gap-4">
      <AllInput inputs={inputs} formData={formData} setFormData={setFormData} />

      <SuccessDialog
        title="Procurement request created successfully"
        description={
          <>
            Procurement Request for Order No {formData.orderNumber}, have been
            successfully created
          </>
        }
      >
        <Button className="my-4 w-full">Create Request</Button>
      </SuccessDialog>
    </form>
  );
};

export default NewProcurementRequestForm;
